{% set pyproject = load_file_data('pyproject.toml') %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}

package:
  name: {{ poetry.get('name') }}
  version: {{ poetry.get('version') }}

about:
  home: {{ poetry.get('homepage') }}
  license: {{ poetry.get('license') }}
  summary: {{ poetry.get('description') }}
  description: |
    Audio Separator is a Python package that allows you to separate an audio file into two stems, primary and secondary, using a model in the ONNX format trained by @Anjok07 for use with UVR (https://github.com/Anjok07/ultimatevocalremovergui).
  doc_url: {{ poetry.get('documentation') }}
  dev_url: {{ poetry.get('homepage') }}

extra:
  recipe-maintainers:
    - beveradb
  authors:
    {% for author in poetry['authors'] %}
    - '{{ author }}>'
    {% endfor %}
  classifiers:
    {% for classifier in poetry['classifiers'] %}
    - '{{ classifier }}'
    {% endfor %}

source:
    path: ..

build:
  script: pip install . -vv --no-deps --no-build-isolation

  entry_points:
    {% for script in poetry['scripts'] %}
    - '{{ script }}={{ poetry['scripts'][script] }}'
    {% endfor %}

requirements:
  host:
    - python >=3.9
    - pip
    - poetry
    - llvmlite
  run:
    - python >=3.9
    - requests
    - numpy
    - librosa
    - six
    - pydub
    - pytorch
    - torchvision
    - torchaudio
    - ffmpeg >=6
    - onnx
    - onnxruntime
    - onnx2torch
