name: run-tests

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests
        run: pytest tests/unit

      # - name: Run integration tests
      #   run: pytest tests/integration
      # - name: Run end-to-end tests
      #   run: pytest tests/end_to_end
